### ISSUE TITLE
Implement Authentication

### ISSUE THREAD

**Issue by DrSayre** [CornerstoneIO/cornerstone-ui#2] opened 2017-04-12 14:26 UTC
See these videos to get a sense on how to do it https://www.emberscreencasts.com/tags/authentication

**Comment by DrSayre** [comment] 2017-04-12 14:31
I can make a branch that uses authentication and @b00tahead can look at it to make sure we use it correctly with what he has created already.

**Comment by DrSayre** [comment] 2017-04-17 00:38
I hope to have this done tomorrow.  I did this awhile ago but must have forgot some steps on the Ember side.  Also @b00tahead do you use a plugin or addon for handling a cookie?  I tried installing js-cookie and got an error.

**Comment by b00tahead** [comment] 2017-04-17 12:43
What's the error that you're getting? I probably wouldn't use the same addon that I used for Engage. I would probably suggest something with a higher rating like [ember-cookies](https://www.npmjs.com/package/ember-cookies).

**Comment by DrSayre** [comment] 2017-04-17 13:02
Cannot find module 'internal/fs'

**Comment by b00tahead** [comment] 2017-04-26 01:32
Closing as duplicate of #3

**Closed as completed by b00tahead** 2017-04-26 01:32 UTC
Labels: duplicate, authentication
